swagger_parser:
  schema_path: openapi.json
  # schema_url: https://raw.githubusercontent.com/Kareadita/Kavita/refs/tags/v0.8.9/openapi.json
  output_directory: lib/api
  json_serializer: freezed
  client_postfix: Client
  put_clients_in_folder: true
  put_in_folder: true

  use_freezed3: true
  unknown_enum_value: true
  enums_to_json: false
  infer_required_from_nullable: false
  include_if_null: false

  include_tags:
    - Account
    - Book
    - Chapter
    - Image
    - Library
    - Reader
    - Series
    - Plugin

  exclude_tags:
    - exclude
