name: CI
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: apk --debug
          - os: ubuntu-latest
            platform: web
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: ios --no-codesign
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v6

      - name: Get FVM Configuration ğŸ”§
        uses: kuhnroyal/flutter-fvm-config-action@v3
        id: fvm-config-action

      - name: Setup Flutter ğŸ“¦
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true

      - name: Install Linux Dependencies ğŸ§
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Code Generation ğŸ§¬
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze ğŸ”
        run: flutter analyze

      - name: Build ğŸ—ï¸
        run: flutter build ${{ matrix.platform }}

      - name: Test ğŸ§ª
        run: flutter test
